server:
  port: 7788 #服务端口
spring:
  application:
    name: config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/tony198998/spring-cloud.git
          search-paths: config-repo		#配置文件目录地址
          username: tony198998	#github账号（公有项目不需要设置）
          password: ji6492194 	#github密码（公有项目不需要设置）
      #label: master	#分支名称