server:
  port: 9411

#zipkin服务所在地址
spring:
  application:
    name: cloud-zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false

###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://tony:123456@127.0.0.1:8100/eureka,http://tony:123456@127.0.0.1:9100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
