server:
  port: 9100
spring:
  application:
    name: eureka-center
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: tony
      password: 123456

eureka:
  instance:
    #注册中心地址
    hostname: 127.0.0.1
  ###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    ###是否将自己注册到Eureka服务中,集群的时候为true
    register-with-eureka: true
    fetch-registry: true
  ###测试环境、开发环境可以关闭自我保护机制，保证服务不可用时及时剔除
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

